"""Animation manifest — maps state names to LINEAR frame ranges in a sprite sheet.

Frames flow left->right, top->bottom across `columns` (Aseprite's by-rows export),
so a state is a [from, to] index range; the loader computes each frame's (row, col)
as (idx // columns, idx % columns). Pure-Python (no Qt), import-safe everywhere.

`aliases` maps the body's canonical states (idle/walk/run/sleep/happy/…) to the
real tag names in the pack, so the LLM-driven verbs/emotions resolve to real art.
Anything still missing falls back via FALLBACKS.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import yaml

# canonical states the body/verbs/emotions request
CANONICAL_STATES = [
    "idle", "walk", "run", "sleep", "sit", "lie", "stretch", "lick",
    "happy", "angry", "scared", "excited", "bored", "curious", "look", "pounce",
    "nudge", "fall", "watch",
]

# requested-name -> a state likely to exist, if the requested one is missing
FALLBACKS = {
    "run": "walk", "chase": "run", "follow_cursor": "walk", "walk_to": "walk",
    "look": "idle", "look_at": "idle", "watch": "sit", "nap": "sleep",
    "sit_on": "sit", "pounce": "run", "nudge": "walk", "hide": "sit",
    "stretch": "idle", "lick": "idle", "lie": "sleep", "scared": "idle",
    "excited": "happy", "bored": "idle", "curious": "idle", "annoyed": "angry",
    "mischievous": "happy", "affectionate": "happy", "sleepy": "sleep",
    "neutral": "idle",
}


@dataclass
class AnimSpec:
    state: str
    frm: int = 0
    to: int = 0
    fps: float = 10.0
    loop: bool = True
    sheet: Optional[str] = None  # override; defaults to the manifest sheet
    cells: Optional[list[int]] = None  # explicit cell indices (for non-contiguous tags)

    @property
    def count(self) -> int:
        if self.cells:
            return max(1, len(self.cells))
        return max(1, self.to - self.frm + 1)

    @property
    def cell_list(self) -> list[int]:
        """The physical sheet cells this animation occupies, in play order."""
        return list(self.cells) if self.cells else list(range(self.frm, self.to + 1))


@dataclass
class Manifest:
    frame_w: int = 32
    frame_h: int = 32
    columns: int = 10
    sheet: str = ""
    specs: dict[str, AnimSpec] = field(default_factory=dict)
    aliases: dict[str, str] = field(default_factory=dict)

    def get(self, state: str) -> Optional[AnimSpec]:
        if state in self.specs:
            return self.specs[state]
        if state in self.aliases and self.aliases[state] in self.specs:
            return self.specs[self.aliases[state]]
        seen = set()
        cur = state
        while cur in FALLBACKS and cur not in seen:
            seen.add(cur)
            cur = FALLBACKS[cur]
            if cur in self.specs:
                return self.specs[cur]
            if cur in self.aliases and self.aliases[cur] in self.specs:
                return self.specs[self.aliases[cur]]
        return self.specs.get("idle") or next(iter(self.specs.values()), None)


def resolve_state(name: str, available: set[str]) -> str:
    """Map a requested anim/verb/emotion name to an available state via fallbacks."""
    if name in available:
        return name
    seen = set()
    cur = name
    while cur in FALLBACKS and cur not in seen:
        seen.add(cur)
        cur = FALLBACKS[cur]
        if cur in available:
            return cur
    return "idle" if "idle" in available else next(iter(available), "idle")


def load(path: str | Path) -> Optional[Manifest]:
    p = Path(path)
    if not p.exists():
        return None
    with open(p, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    fw, fh = (data.get("frame_size") or [32, 32])[:2]
    columns = int(data.get("columns", 10))
    sheet = data.get("sheet", "")
    default_fps = float(data.get("default_fps", 10))
    specs: dict[str, AnimSpec] = {}
    for state, d in (data.get("states") or {}).items():
        cells = d.get("frames")
        cells = [int(c) for c in cells] if cells else None
        specs[state] = AnimSpec(
            state=state,
            frm=int(d.get("from", (cells[0] if cells else 0))),
            to=int(d.get("to", (cells[-1] if cells else d.get("from", 0)))),
            fps=float(d.get("fps", default_fps)),
            loop=bool(d.get("loop", True)),
            sheet=d.get("sheet"),
            cells=cells,
        )
    aliases = dict(data.get("aliases") or {})
    return Manifest(frame_w=int(fw), frame_h=int(fh), columns=columns,
                    sheet=sheet, specs=specs, aliases=aliases)


def default_manifest_yaml() -> str:
    """Starter manifest (used only if none exists). Real packs are generated by
    deskpet.tools.aseprite_to_manifest."""
    return (
        "# Starter manifest. For the Bow.Pixel 'Cat 85+' pack, generate the real one:\n"
        "#   python -m deskpet.tools.aseprite_to_manifest <file.aseprite> <sheet.png> \\\n"
        "#     --out assets/anim_manifest.yaml --sheet-rel <relative/sheet.png>\n"
        "sheet: cat.png\n"
        "frame_size: [32, 32]\n"
        "columns: 10\n"
        "default_fps: 10\n"
        "states:\n"
        "  idle: { from: 0, to: 3, fps: 6, loop: true }\n"
        "  walk: { from: 4, to: 9, fps: 10, loop: true }\n"
        "aliases: {}\n"
    )
